### ISSUE TITLE
Include rabbitmq-server in VM

### ISSUE THREAD

**Issue by mikeconley** [smacleod/rb-vm-dev#3]
I believe vagrant allows us to pre-install some things on the VM. Or specify things to be installed on first run of the VM. We should add rabbitmq-server to that list.

http://www.rabbitmq.com/install-debian.html

**Comment by smacleod** [comment]
This already happens. If you go into the vagrantfile you can switch to Review Bot recipes which will give you what you need for it.

https://github.com/smacleod/rb-vm-dev/blob/f685710d836864dac2975ad76b32822e1474789a/Vagrantfile#L52-L53
